# Generated by Django 3.1.2 on 2020-10-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tabela_testowa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tabela_testowa',
            new_name='SystemState',
        ),
    ]
